# Spring配置
spring:
  profiles:
    include:
      - database
      - mybatis
      - sql-configuration

# 日志配置
logging:
  level:
    com.rukawa.gernerate.sql.mapper: debug

# 图片配置
image:
  location: file:images/

# 系统配置
system:
  expire: 1800

# 默认用户信息
user:
  userHead: /images/user.png
  roleId: 1